name: 'build direwolf'

on:
  workflow_dispatch:
    inputs:
      cmake_flags:
        description: 'Custom CMAKE flags'
        required: false
  push:
    paths-ignore:
      - '.github/**'
  pull_request:
    paths-ignore:
      - '.github/**'

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
              name: 'Windows Latest MinGW 64bit',
              os: windows-latest,
              cc: 'gcc',
              cxx: 'g++',
              arch: 'x86_64',
              msys_sys: 'MINGW64',
              build_type: 'Release',
              cmake_extra_flags: '-G "MinGW Makefiles"'
            }
          - {
              name: 'Windows Latest MinGW 32bit',
              os: windows-latest,
              cc: 'gcc',
              cxx: 'g++',
              arch: 'i686',
              msys_sys: 'MINGW32',
              build_type: 'Release',
              cmake_extra_flags: '-G "MinGW Makefiles"'
            }
          - {
              name: 'macOS latest',
              os: macos-latest,
              cc: 'clang',
              cxx: 'clang++',
              arch: 'x86_64',
              build_type: 'Release',
              cmake_extra_flags: ''
            }
          - {
              name: 'Ubuntu latest Debug',
              os: ubuntu-latest,
              cc: 'gcc',
              cxx: 'g++',
              arch: 'x86_64',
              build_type: 'Debug',
              cmake_extra_flags: ''
            }

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup MSYS2
        if: matrix.config.msys_sys != ''
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.config.msys_sys }}
          install: >-
            mingw-w64-${{ matrix.config.arch }}-gcc
            mingw-w64-${{ matrix.config.arch }}-cmake
            mingw-w64-${{ matrix.config.arch }}-make
            mingw-w64-${{ matrix.config.arch }}-pkg-config
            mingw-w64-${{ matrix.config.arch }}-tools-git

      - name: Install dependencies (Linux/macOS)
        if: matrix.config.msys_sys == '' && runner.os != 'Windows'
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt-get update
            sudo apt-get install -y libasound2-dev libudev-dev libhamlib-dev gpsd
          elif [ "$RUNNER_OS" == "macOS" ]; then
            brew install portaudio hamlib gpsd hidapi
          fi

      - name: create build environment
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: configure
        # If msys_sys is set, use msys2 shell, otherwise use bash
        shell: ${{ matrix.config.msys_sys != '' && 'msys2 {0}' || 'bash' }}
        working-directory: ${{github.workspace}}/build
        run: |
          cmake $GITHUB_WORKSPACE \
            -DCMAKE_BUILD_TYPE=${{ matrix.config.build_type }} \
            -DCMAKE_C_COMPILER=${{ matrix.config.cc }} \
            -DCMAKE_CXX_COMPILER=${{ matrix.config.cxx }} \
            -DCMAKE_CXX_FLAGS="-Werror" -DUNITTEST=1 \
            ${{ matrix.config.cmake_extra_flags }} \
            ${{ github.event.inputs.cmake_flags }}

      - name: build
        shell: ${{ matrix.config.msys_sys != '' && 'msys2 {0}' || 'bash' }}
        working-directory: ${{github.workspace}}/build
        run: |
          cmake --build . --config ${{ matrix.config.build_type }}

      - name: test
        continue-on-error: true
        shell: ${{ matrix.config.msys_sys != '' && 'msys2 {0}' || 'bash' }}
        working-directory: ${{github.workspace}}/build
        run: |
          ctest -C ${{ matrix.config.build_type }} \
            --parallel 2 --output-on-failure

      - name: package
        shell: ${{ matrix.config.msys_sys != '' && 'msys2 {0}' || 'bash' }}
        working-directory: ${{github.workspace}}/build
        run: |
          if [[ "$OSTYPE" == "darwin"* ]] || [[ "$MSYSTEM" != "" ]]; then
            cmake --build . --target package
          fi

      - name: archive binary
        uses: actions/upload-artifact@v4
        with:
          name: direwolf_${{ matrix.config.os }}_${{ matrix.config.arch }}_${{ github.sha }}
          path: |
            ${{github.workspace}}/build/direwolf-*.zip
            ${{github.workspace}}/build/direwolf.conf
            ${{github.workspace}}/build/src/*.exe
            ${{github.workspace}}/build/src/direwolf
            ${{github.workspace}}/build/CMakeCache.txt
