name: 'build direwolf'

on:
  workflow_dispatch:
    inputs:
      cmake_flags:
        description: 'Custom CMAKE flags'
        required: false
  push:
    paths-ignore:
      - '.github/**'
  pull_request:
    paths-ignore:
      - '.github/**'

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
              name: 'Windows Latest MinGW 32bit',
              os: windows-latest,
              arch: 'i686',
              mingw_platform: 'x86',
              build_type: 'Release',
              cmake_extra_flags: '-G "MinGW Makefiles"'
            }

    steps:
      - name: checkout
        uses: actions/checkout@v6

      # Use the specific MinGW installer action for Windows
      - name: Install MinGW
        if: runner.os == 'Windows'
        uses: egor-tensin/setup-mingw@v3
        with:
          platform: ${{ matrix.config.mingw_platform }}

      - name: dependency
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt-get update
            sudo apt-get install -y libasound2-dev libudev-dev libhamlib-dev gpsd
          elif [ "$RUNNER_OS" == "macOS" ]; then
            brew install portaudio hamlib gpsd hidapi
          fi

      - name: create build environment
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: configure
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: |
          # No need for manual PATH exports; install-mingw handles it.
          cmake $GITHUB_WORKSPACE \
            -DCMAKE_BUILD_TYPE=${{ matrix.config.build_type }} \
            -DCMAKE_CXX_FLAGS="-Werror" -DUNITTEST=1 \
            ${{ matrix.config.cmake_extra_flags }} \
            ${{ github.event.inputs.cmake_flags }}

      - name: build
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: |
          cmake --build . --config ${{ matrix.config.build_type }}

      - name: test
        continue-on-error: true
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: |
          ctest -C ${{ matrix.config.build_type }} --parallel 2 --output-on-failure

      - name: package
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: |
          if [ "$RUNNER_OS" != "Linux" ]; then
            cmake --build . --target package
          fi

      - name: archive binary
        uses: actions/upload-artifact@v7
        with:
          name: direwolf_${{ matrix.config.os }}_${{ matrix.config.arch }}_${{ github.sha }}
          path: |
            ${{github.workspace}}/build/direwolf-*.zip
            ${{github.workspace}}/build/direwolf.conf
            ${{github.workspace}}/build/src/*
            ${{github.workspace}}/build/CMakeCache.txt
            !${{github.workspace}}/build/src/cmake_install.cmake
            !${{github.workspace}}/build/src/CMakeFiles
            !${{github.workspace}}/build/src/Makefile
